# **Practicing Pandas**

**Importing Libraries**

In [2]:
import pandas as pd

**Importing Dataset**

In [3]:
data = pd.read_csv("penguins.csv")

**Head()**

In [4]:
data.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [5]:
data.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

**tail()**

In [6]:
data.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

**shape**

In [7]:
data.shape

(344, 7)

**info()**

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

**describe()**

In [9]:
data.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

**Columns**

In [10]:
data.columns

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

**dtypes**

In [11]:
data.dtypes

species               object
island                object
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                   object
dtype: object

**value_counts**

In [12]:
data['sex'].value_counts()

sex
MALE      168
FEMALE    165
.           1
Name: count, dtype: int64

In [13]:
data['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

**isna()**

In [14]:
data.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

**fillna()**

In [15]:
data['bill_length_mm']=data['bill_length_mm'].fillna(data['bill_length_mm'].mean())

In [16]:
data.isna().sum()

species               0
island                0
bill_length_mm        0
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

**dropna()**

In [17]:
data = data.dropna()

In [18]:
data.shape

(334, 7)

**duplicated / Drop_duplicated**

In [19]:
data.duplicated().sum()

np.int64(0)

**iloc**

In [20]:
data.iloc[:,0:3]

    species     island  bill_length_mm
0    Adelie  Torgersen            39.1
1    Adelie  Torgersen            39.5
2    Adelie  Torgersen            40.3
4    Adelie  Torgersen            36.7
5    Adelie  Torgersen            39.3
..      ...        ...             ...
338  Gentoo     Biscoe            47.2
340  Gentoo     Biscoe            46.8
341  Gentoo     Biscoe            50.4
342  Gentoo     Biscoe            45.2
343  Gentoo     Biscoe            49.9

[334 rows x 3 columns]

**drop()**

In [21]:
data=data.drop(("flipper_length_mm"),axis=1)

In [22]:
data.shape

(334, 6)

**sort_values()**

In [23]:
data.sort_values(by='bill_length_mm')

       species     island  bill_length_mm  bill_depth_mm  body_mass_g     sex
142     Adelie      Dream            32.1           15.5       3050.0  FEMALE
98      Adelie      Dream            33.1           16.1       2900.0  FEMALE
70      Adelie  Torgersen            33.5           19.0       3600.0  FEMALE
92      Adelie      Dream            34.0           17.1       3400.0  FEMALE
18      Adelie  Torgersen            34.4           18.4       3325.0  FEMALE
..         ...        ...             ...            ...          ...     ...
335     Gentoo     Biscoe            55.1           16.0       5850.0    MALE
215  Chinstrap      Dream            55.8           19.8       4000.0    MALE
321     Gentoo     Biscoe            55.9           17.0       5600.0    MALE
169  Chinstrap      Dream            58.0           17.8       3700.0  FEMALE
253     Gentoo     Biscoe            59.6           17.0       6050.0    MALE

[334 rows x 6 columns]

In [24]:
data.sort_values(by='bill_length_mm',ascending = False)

       species     island  bill_length_mm  bill_depth_mm  body_mass_g     sex
253     Gentoo     Biscoe            59.6           17.0       6050.0    MALE
169  Chinstrap      Dream            58.0           17.8       3700.0  FEMALE
321     Gentoo     Biscoe            55.9           17.0       5600.0    MALE
215  Chinstrap      Dream            55.8           19.8       4000.0    MALE
335     Gentoo     Biscoe            55.1           16.0       5850.0    MALE
..         ...        ...             ...            ...          ...     ...
18      Adelie  Torgersen            34.4           18.4       3325.0  FEMALE
92      Adelie      Dream            34.0           17.1       3400.0  FEMALE
70      Adelie  Torgersen            33.5           19.0       3600.0  FEMALE
98      Adelie      Dream            33.1           16.1       2900.0  FEMALE
142     Adelie      Dream            32.1           15.5       3050.0  FEMALE

[334 rows x 6 columns]

**groupby()**

In [25]:
data.groupby(by='species')['bill_length_mm'].mean()

species
Adelie       38.823973
Chinstrap    48.833824
Gentoo       47.542500
Name: bill_length_mm, dtype: float64